FROM joooohnson/redis_base:v2
MAINTAINER johnson "zhangwangqing@163.com"
ENV REFRESHED_AT 2017-8-21

ENTRYPOINT [ "/usr/bin/redis-server","/etc/redis/redis.conf","--logfile /var/log/redis/redis-server.log" ]
